[tox]
envlist = py310,py311,py312,py313,py314,sdist
requires =
    tox>4

[gh]
python =
    3.14 = py314, sdist
    3.13 = py313
    3.12 = py312
    3.11 = py311
    3.10 = py310

[testenv]
package = wheel
deps = pytest==8.4.2
commands = pytest tests {posargs}

[testenv:sdist]
package = sdist
